name: Release

on:
  push:
    branches-ignore:
      - '*'
    tags:
      - '*.*.*' # push to versioned tag will trigger this build

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Windows x64",
            os: windows-latest,
            build_command: "cmd.exe /c '\"C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat\" && build.bat x64'",
            archive_name: "tonclient_dotnet_bridge_windows_x64"
          }
          - {
            name: "Windows x86",
            os: windows-latest,
            init_command: "rustup install stable-i686-pc-windows-msvc",
            build_command: "cmd.exe /c '\"C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars32.bat\" && build.bat x86'",
            archive_name: "tonclient_dotnet_bridge_windows_x86"
          }
          - {
            name: "Ubuntu x64",
            os: ubuntu-latest,
            build_command: "./build.sh",
            archive_name: "tonclient_dotnet_bridge_linux_x64"
          }
          - {
            name: "macOS x64",
            os: macos-latest,
            build_command: "./build.sh",
            archive_name: "tonclient_dotnet_bridge_macos_x64"
          }

    steps:
      - uses: actions/checkout@v1

      - name: Set version
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Init
        if: matrix.config.init_command
        run: |
          ${{ matrix.config.init_command }}

      - name: Build
        run: |
          ${{ matrix.config.build_command }} ${{ steps.vars.outputs.tag }}

      - name: Upload Logs
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          path: |
            vendor/build/ton-sdk-${{ steps.vars.outputs.tag }}/src/ton-sdk-stamp/ton-sdk-build-*.log
          name: build-logs

      - name: Upload Library Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.config.archive_name }}
          path: |
            install
